
- name: setup stack
  hosts: stack
  gather_facts: true
  become: true
  vars:
    app:
      src: ./app/
      dest: /opt/fastapi/
      owner: fastapi_user
      description: simple fastapi app using a mysql database
      app_port: "8000"
    mysql:
      bind_address: '0.0.0.0'
  tasks:
      - name: '[FRONTEND] install configure apache2'
        ansible.builtin.include_tasks:
          file: ./tasks/apache.yml
        when: "'frontend' in group_names"

      - name: '[DB] Install configure mysql database'
        ansible.builtin.include_tasks:
          file: ./tasks/mysql.yml
        when: "'db' in group_names"

      - name: '[BACKEND] Install configure backends'
        ansible.builtin.include_tasks:
          file: ./tasks/app.yml
        when: "'backend' in group_names"