- name: setup stack
  hosts: stack
  gather_facts: true
  become: true
  vars:
    app:
      src: ./app/
      dest: /opt/fastapi/
      owner: fastapi_user
      description: simple fastapi app using a mysql database
      app_port: "8000"
    mysql:
      bind_address: '0.0.0.0'
    log_path: /var/log/
    scripts_path: /opt/scripts/
    aws_remote_user: ubuntu
  tasks:
      - name: '[LOADBALANCER] Install configure apache2'
        ansible.builtin.include_tasks:
          file: ./tasks/apache.yml
        when: "'loadbalancer' in group_names"

      - name: '[DATABASE] Install configure mysql database'
        ansible.builtin.include_tasks:
          file: ./tasks/mysql.yml
        when: "'database' in group_names"

      - name: '[BACKEND] Install configure backends'
        ansible.builtin.include_tasks:
          file: ./tasks/app.yml
        when: "'backend' in group_names"
      
      - name: '[DOCTOR] Configure heartbeat service'
        ansible.builtin.include_tasks:
          file: ./tasks/doctor.yml
        when: "'doctor' in group_names"

- name: Configure patients
  hosts: patients
  become: yes
  tasks:
    - name: '[PATIENTS] Configure patients'
      ansible.builtin.include_tasks:
        file: ./tasks/patient.yml

- name: local action
  hosts: localhost
  connection: local
  become: no
  tasks: 
      - name: Clean up
        ansible.builtin.file:
          path: /tmp/pub_key
          state: absent
        