- name: install apache2
  ansible.builtin.apt:
    name:
      - apache2
    state: present
    update_cache: yes
    cache_valid_time: 3600
- name: render and copy vhost config file for apache webserver
  ansible.builtin.template:
    src: apache_vhost.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: root
    group: root
    mode: 0644
- name: enable plugins for apache webserver
  ansible.builtin.command:
    cmd: | 
      a2enmod proxy proxy_ajp proxy_http rewrite deflate
      headers proxy_balancer proxy_connect proxy_html lbmethod_byrequests
- ansible.builtin.command:
    cmd: curl https://icanhazip.com/
  register: ip_number
  delegate_to: localhost
  connection: local
  become: no
- name: enable server status page
  ansible.builtin.replace:
    path: /etc/apache2/mods-enabled/status.conf
    regexp: '#Require ip 192.0.2.0/24'
    replace: 'Require ip {{ ip_number.stdout }}/32'
- name: restart service
  ansible.builtin.service:
    name: apache2
    state: restarted
    