- name: install apache2
  ansible.builtin.apt:
    name:
      - apache2
      - certbot
      - python3-certbot-apache
    state: present
    update_cache: yes
    cache_valid_time: 3600
- name: enable plugins for apache webserver
  ansible.builtin.command:
    cmd: | 
      a2enmod proxy proxy_ajp proxy_http rewrite deflate
      headers proxy_balancer proxy_connect proxy_html lbmethod_byrequests
- ansible.builtin.command:
    cmd: curl https://icanhazip.com/
  register: ip_number
  delegate_to: localhost
  connection: local
  become: no
- name: enable server status page
  ansible.builtin.replace:
    path: /etc/apache2/mods-enabled/status.conf
    regexp: '#Require ip 192.0.2.0/24'
    replace: 'Require ip {{ ip_number.stdout }}/32'
- name: update DNS
  ansible.builtin.shell:
    cmd: |
     echo url="https://www.duckdns.org/update?domains={{ domain }}&token={{ dns.token }}
     &ip=" | curl -k -K - && echo ""
- name: render and copy vhost config file for apache webserver
  ansible.builtin.template:
    src: apache_vhost.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: root
    group: root
    mode: 0644
- name: enable HTTPS
  ansible.builtin.command:
    cmd: certbot --apache -n --domains {{ fqdn }} --agree-tos --email {{ email }}
  ignore_errors: yes
- name: render and copy vhost ssl config file for apache webserver
  ansible.builtin.template:
    src: apache_vhost_ssl.j2
    dest: /etc/apache2/sites-enabled/000-default-le-ssl.conf
    owner: root
    group: root
    mode: 0644
- name: restart service
  ansible.builtin.service:
    name: apache2
    state: restarted